version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - celery
    env_file:
      - .env
    command: >
      /bin/sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "celery", "-A", "src.services.celery_app.celery", "worker", "--loglevel=info" ]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis
      - celery

volumes:
  postgres_data: