name: Test

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          USER_SECRET_KEY: ${{ secrets.USER_SECRET_KEY }}
          PERSPECTIVE_API_KEY: ${{ secrets.PERSPECTIVE_API_KEY }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
          CELERY_BACKEND_URL: ${{ secrets.CELERY_BACKEND_URL }}
        timeout-minutes: 5
        run: pytest
